blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/sedkichayata/chess/discussions
    about: Please use GitHub Discussions for questions and general discussions
